import pic from 'src/assets/images/cardImages/activityImage.png';
import pic1 from 'src/assets/images/cardImages/activityImage1.png';
import pic2 from 'src/assets/images/cardImages/activityImage2.png';
import pic3 from 'src/assets/images/cardImages/activityImage3.png';
import pic4 from 'src/assets/images/cardImages/activityImage4.png';
import pic5 from 'src/assets/images/cardImages/activityImage5.png';

export const activityCardsArr = [
	{
		saleType: 'cancellation',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
	{
		saleType: 'sale',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic1,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
	{
		saleType: 'listing',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic1,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
	{
		saleType: 'cancellation',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic2,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
	{
		saleType: 'cancellation',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic3,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
	{
		saleType: 'cancellation',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic4,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
	{
		saleType: 'cancellation',
		cardNum: '#3523',
		etherPrice: '94.23',
		diamondPrice: '593',
		starPrice: '5',
		viewTransaction: false,
		image: pic5,
		cardTitle: 'Bored Ape Yacht Club',
		cardTime: '5 min ago',
		cardDate: '04/06/2022',
	},
];
