import pic from 'src/assets/images/home/tableNFT/nft1.png';

export const leaderBoardCardsArr = [
    {
        cardNumber: 1,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 2,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 3,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 4,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 5,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 6,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 7,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 8,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 9,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 10,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 11,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
    {
        cardNumber: 12,
        walletAddress: '0x9dcC...5B71',
        cardUserImg: pic,
        portfolioValue: 197.7,
        pnl: 57.342,
        winningTrades: 9,
        losingTrades: 5,
        spent: '$322K',
        mints: 494,
    },
];
