export const GET_ALL_SEND_CARDS = 'GET_ALL_SEND_CARDS';
export const SELECT_ITEM_OF_SEND_CARDS = 'SELECT_ITEM_OF_SEND_CARDS';
export const REMOVE_ITEM_OF_SEND_CARDS = 'REMOVE_ITEM_OF_SEND_CARDS';
export const REMOVE_ALL_ITEMS_OF_SEND_CARDS = 'REMOVE_ALL_ITEMS_OF_SEND_CARDS';
export const GET_TOTAL_AMOUNT_OF_NFTS = 'GET_TOTAL_AMOUNT_OF_NFTS';
