export const CHANGE_CART_OPEN_OF_APP = 'CHANGE_CART_OPEN_OF_APP';
export const CHANGE_SWEEP_OPEN_OF_APP = 'CHANGE_SWEEP_OPEN_OF_APP';
export const CHANGE_POPUP_OPEN_OF_APP = 'CHANGE_POPUP_OPEN_OF_APP';
export const CHANGE_VISIT_COUNT_OF_APP = 'CHANGE_VISIT_COUNT_OF_APP';
