import pic from 'src/assets/images/cardImages/activityImage.png';

export const dataArr = [
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
	{
		image: pic,
		cardNumber: '#3867',
		starPrice: 3,
		diamondPrice: 593,
		etherPrice: 94.23,
		estimated: 144,
		pricePercent: '4%',
		id: crypto.randomUUID(),
	},
];
